eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: clientes
            uri: http://localhost:8082
            predicates:
              - Path=/api/clientes/**
          - id: cuentas
            uri: http://localhost:8081
            predicates:
              - Path=/api/cuentas/**
          - id: movimientos
            uri: http://localhost:8081
            predicates:
              - Path=/api/movimientos/**
          - id: reportes
            uri: http://localhost:8081
            predicates:
              - Path=/api/reportes/**

  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8080


